-- Create table note for saving todo notes
CREATE TABLE note (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    create_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    update_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    status          VARCHAR(16) NOT NULL,
    finishing_time  TIMESTAMP WITH TIME ZONE,
    text            VARCHAR(120) NOT NULL
);

-- Add index for searchable columns
CREATE INDEX idx_note_status            ON note (status);
CREATE INDEX idx_note_create_time       ON note (create_time);
CREATE INDEX idx_note_finishing_time    ON note (finishing_time);
