CREATE TABLE note_dto (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    create_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    update_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    status          SMALLINT NOT NULL,
    finishing_time  TIMESTAMP WITH TIME ZONE,
    text            TEXT NOT NULL
);
