services:
  tododb:
    container_name: tododb
    image: postgres:18.3-trixie
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todopassword
      POSTGRES_DB: todo
    ports:
      - '5432:5432'
    volumes:
      - tododb-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U todo -d todo']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tododb-data:
