# Build the jar
FROM maven:3.9-eclipse-temurin-25 AS build-stage

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

# Run the jar
FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build-stage /app/target/todoserver-1.0-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
